In [16]:
!git clone https://wayo116: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@github.com/wayo116/2306_l6.git
#!pip install umap-learn

optuna_flag = 0
if optuna_flag:
    !pip install optuna
    model_type = "light_gbm_optuna"

else:
    model_type = "light_gbm"

import os
import csv
import time

os.chdir('/content/2306_l6')

from datalists import dlists
from Utility.inner_outer import combi
from Dell6_v2 import Dell6
from Utility.LightgbmPack import LightgbmPack
from Utility.datalists_check import datalists_check
from Utility.per_hyouji import per_hyouji

start = time.time()

kekka_matomes = []

kaisai = 10
if kaisai == -1:
    st = -1
    ed = 0
elif kaisai == 0:
    st = 0
    ed = 1
elif kaisai > 0:
    st = 1
    ed = kaisai + 1

dlists_shoki = dlists

for kaisai in range(st,ed):
    print("\nkaisai",kaisai)
    dlists = dlists_shoki
    if kaisai == -1:
        #本番
        #最新結果がgitjubに登録済の時
        saisinkekka_list=[99,99,99,99,99,99]
        dlists = dlists_shoki
    elif kaisai == 0:
        #最新結果がcolabにはあるが、gitjubには未登録の時
        saisinkekka_list=[7,8,12,25,30,32]
        dlists = dlists_shoki
    elif kaisai > 0:
        saisinkekka_list = dlists_shoki[kaisai-1]
        dlists = dlists_shoki[kaisai:]
    print("saisinkekka_list",saisinkekka_list)
    print("dlists",dlists[:5])

    bunkatu=5

    print('\n----vol 1----')
    # 初期値
    dlists_end = 100
    predictions_all = []
    lgbm_obj = LightgbmPack()
    params = {"dataset_params":{"study_range_start":-0.01,
                                "study_range_end":0.01,
                                "study_nmasi":6,
                                "test_range_start":-3,
                                "test_range_end":3,
                                "test_nmasi":3,
                                "bunseki_hani":2,
                                "flat_hani":2,
                                "z_thresh":2,
                                "test_dlists_hani":[0],},

                "lgbm_model":{"model_type":model_type,},

                "lgbm_params":{'objective': 'multiclass',
                                'num_class': 43,
                                'boosting_type': 'gbdt',
                                'metric': 'multi_logloss',
                                'num_leaves': 2,
                                'learning_rate': 0.1,
                                'feature_fraction': 1,
                                'max_depth': 7,
                                'random_seed': 42,
                                'force_row_wise': True,
                                'feature_pre_filter': False,
                                'lambda_l1': 5,
                                'lambda_l2': 5,
                                'bagging_fraction': 0.6,
                                'bagging_freq': 1,
                                'min_data_in_leaf': 2,
                                'num_iterations': 100,},
              }

    # 処理
    predictions_all = lgbm_obj.lightgbmpack(kaisai, saisinkekka_list, dlists, dlists_end, **params)

    # 表示
    print("saisinkekka_list",saisinkekka_list)
    predictions_all = sorted(list(map(int, set(predictions_all))))
    print("predictions_all",predictions_all)
    per_hyouji(saisinkekka_list,predictions_all)


    print('\n----vol 2----')
    delall = 0

    # 初期値
    predictions_delall = []

    if delall:
        # 初期値
        predictions_delall = []

        # 処理
        predictions_delall = datalists_check(dlists,len(dlists),1)

        # 表示
        print("saisinkekka_list",saisinkekka_list)
        predictions_delall = sorted(list(map(int, set(predictions_delall))))
        print("predictions_delall",predictions_delall)
        per_hyouji(saisinkekka_list,predictions_delall)


    print('\n----vol 1 2----')
    # 初期値
    predictions_unique = []

    # 処理
    predictions_unique = [item for item in predictions_all if item not in predictions_delall]

    # 表示
    print("saisinkekka_list",saisinkekka_list)
    predictions_unique = sorted(list(map(int, set(predictions_unique))))
    print("predictions_unique",predictions_unique)
    wariai, percent = per_hyouji(saisinkekka_list,predictions_unique)

    pred_dlists = combi(predictions_unique,6)

    #shori2は、pred_dlistsには組合せリストを入れる
    outlist, kankin =Dell6(dlists, pred_dlists, saisinkekka_list, bunkatu).shori2()
    #outlists.extend(outlist)
    #print('outlist',outlist)

    kekka_matomes.append([kaisai, wariai, percent, kankin])

goukei = 0
for kekka_matome in kekka_matomes:
    goukei = goukei + kekka_matome[3]
    print(kekka_matome)
print("goukei",goukei)
print("処理時間",time.time() - start)

fatal: destination path '2306_l6' already exists and is not an empty directory.

kaisai 1
saisinkekka_list [ 7  8 12 25 30 32]
dlists [[11 13 24 26 28 34]
 [15 16 24 26 35 43]
 [ 8  9 10 16 17 39]
 [ 1  8 23 30 36 41]
 [11 15 17 33 36 41]]

----vol 1----
LightgbmPack

----lightGBMで予想----


/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1656
no_dataset_columns 35
len(train_data) 1656
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [39.99 42.99  2.99 ...  0.    0.    1.  ]
 [39.99 42.99  2.99 ...  0.    0.    1.  ]
 [40.   43.    3.   ...  0.    0.    1.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1678
no_dataset_columns 35
len(train_data) 1678
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1685
no_dataset_columns 35
len(train_data) 1685
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1725
no_dataset_columns 35
len(train_data) 1725
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1749
no_dataset_columns 35
len(train_data) 1749
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1744
no_dataset_columns 35
len(train_data) 1744
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1737
no_dataset_columns 35
len(train_data) 1737
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1709
no_dataset_columns 35
len(train_data) 1709
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]]
473
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.
  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 13.
 13.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1692
no_dataset_columns 35
len(train_data) 1692
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [35.99 41.99  5.99 ...  0.    0.    0.  ]
 [36.   42.    6.   ...  0.    0.    0.  ]
 [36.01 42.01  6.01 ...  0.    0.    0.  ]]
516
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.
  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.
  4.  4.  4.  4.  4.  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.
  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.
  7.  7.  7.  7.  7.  7.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.
  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.
 12.

/content/2306_l6/Utility/dataset.py:425: RuntimeWarning: invalid value encountered in divide
  z_scores = np.abs((nolabel_train_data - np.mean(nolabel_train_data, axis=0)) / np.std(nolabel_train_data, axis=0))
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


no_dataset_rows 1706
no_dataset_columns 35
len(train_data) 1706
no_dataset_rows 18
no_dataset_columns 34
len(test_data) 18
model_type light_gbm
[[ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 [ 4.01 12.01  8.01 ...  0.    0.    1.  ]
 [ 3.99 11.99  7.99 ...  0.    0.    1.  ]
 ...
 [37.99 41.99  3.99 ...  0.    0.    0.  ]
 [38.   42.    4.   ...  0.    0.    0.  ]
 [38.01 42.01  4.01 ...  0.    0.    0.  ]]
516
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.
  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.  4.  4.  4.  4.
  4.  4.  4.  4.  4.  4.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.
  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.
  7.  7.  7.  7.  7.  7.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.
  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.
 12.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')