In [1]:
!git clone https://wayo116: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@github.com/wayo116/2306_l6.git

#!pip install scikit-image
# import tensorflow as tf
import os
# import collections,math
#import itertools
os.chdir('/content/2306_l6')

from datalists import dlists
# from Effi_v6 import Effi_TrainPred
# from randam_kaisai import randam_kaisai_multi3
# from find_kaisaihani import find_kaisaihani

from Dell6_v2 import Dell6
from Utility.inner_outer import inner_outer_manu, inner_outer_auto, inner_outer_other_manu, inner_outer_other_auto
from Utility.kfind import kfind, kfind2
from Utility.match_combi import yobu_combi, aisho_combi, yobu_lists, aisho_lists, yobu_dcnt, aisho_dcnt, yobu_aisho_combi

outlists=[]

kaisai = 0
if kaisai == 0:
    #最新結果は未登録の時
    saisinkekka_list=[12,14,18,25,36,42]
    dlists = dlists
elif kaisai > 0:
    saisinkekka_list = dlists[kaisai-1]
    dlists = dlists[kaisai:]
print("saisinkekka_list",saisinkekka_list)
print("dlists",dlists[:5])

'''
print('\n----学習----')

model_name='V2B0'
#model_name='V2B1'
#model_name='V2B0_none'
#model_name='V2B1_none'
#model_name='V2B2_none'
#model_name='V2B3_none'
#model_name='RegY320'

kaisu=100 #100
setcount=1 #1
kaisu_pre=100
setcount_pre=1 #固定
kaisai_list=find_kaisaihani(dlists,[[0,100],[35,100],[18,150]],5)
kaisai_list_pre=find_kaisaihani(dlists,[[0,100],[35,100],[18,150]],5)
#kaisai_list=randam_kaisai_multi3(3,43,1,88,1,[[4,24],[35,50]],[0,0])
#kaisai_list_pre=randam_kaisai_multi3(3,43,1,55,1,[[4,24],[35,50]],[0,0])
pltflag=0
brendflag=0
inflated=35 #35
inflated_pre=1
kosuu=43 #固定
kosuu_pre=6
hw=96
rdmhani=1
compactness = 21
n_segments = 800
youso_list=randam_kaisai_multi3(3,43,1,55,1,[[0,5]],[0,0])

#baseimg_name='base_img' #黒地に緑数字 68*62
#baseimg_name='base_img2' #カラー43種 フリーサイズ
#baseimg_name='base_img2_2' #カラー43種 マスク 96*96
#baseimg_name='base_img3' #タイル1毎色違い43種 フリーサイズ
#baseimg_name='base_img4' #カラーver2 43種 フリーサイズ
#baseimg_name='base_img4_2' #カラーver2 色彩調整43種 224*224
#baseimg_name='base_img5' #カラー5種 サイズフリー
baseimg_name='base_img5_2' #色彩調整5種
#baseimg_name='base_img6' #タイル10毎色違い5種
#baseimg_name='base_img6_2' #タイル5毎色違い9種
#baseimg_name='base_img_rail' #スライドパズルレール43種

effi_trainpred = Effi_TrainPred(model_name,kaisu,kaisu_pre,kaisai_list,kaisai_list_pre,pltflag,brendflag,inflated,inflated_pre,hw,rdmhani,baseimg_name,setcount,setcount_pre,kosuu,kosuu_pre,compactness,n_segments,youso_list)

dlists=dlists
epochs=5 #5
batch_size=32

modelflag=0
if modelflag == 0:
    model = effi_trainpred.effi_train2(dlists,epochs,batch_size)
    model.save('./my_model.h5')

elif modelflag == 1:
    model = tf.keras.models.load_model('./my_model.h5')

print('\n----推論予想----')

select_box=3
index="None"
saisinkekka=saisinkekka_list
bunkatu=5
pred_dlists = effi_trainpred.pred(dlists,model,select_box,index)
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori()
#outlists.extend(outlist)
#print('outlist',outlist)
'''
'''
print('\n----推論以外で予想----')

bunkatu=4
list_all = list(range(1,44))
diff_list = set(pred_dlists) ^ set(list_all)
outlist=Dell6(dlists, diff_list, saisinkekka, bunkatu).shori()
#outlists.extend(outlist)
#print('outlist',outlist)
'''
#'''
print('\n----inner_outer_manuで予想----')

saisinkekka=saisinkekka_list
bunkatu=5

in_hani=[0,1]
out_hani=[5,15]
in_combisu=1
out_combisu=5
pred_dlists=inner_outer_manu(dlists,in_hani,out_hani,in_combisu,out_combisu)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)

print('\n----inner_outer_autoで予想----')

saisinkekka=saisinkekka_list
bunkatu=5
inner_idxs,outer_idxs = kfind2(dlists,10)

in_hani=inner_idxs
out_hani=outer_idxs
in_combisu=5
out_combisu=1
pred_dlists=inner_outer_auto(dlists,in_hani,out_hani,in_combisu,out_combisu)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)

print('\n----inner_outer_other_manuで予想----')

saisinkekka=saisinkekka_list
bunkatu=5

in_hani=[0,10]
out_hani=[20,30]
in_combisu=4
out_combisu=1
notinout_combisu=1
pred_dlists=inner_outer_other_manu(dlists,in_hani,out_hani,in_combisu,out_combisu,notinout_combisu)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)

print('\n----inner_outer_other_autoで予想----')

saisinkekka=saisinkekka_list
bunkatu=5

inner_idxs,outer_idxs = kfind2(dlists,10)

in_hani=inner_idxs
out_hani=outer_idxs
in_combisu=4
out_combisu=1
notinout_combisu=1
pred_dlists=inner_outer_other_auto(dlists,in_hani,out_hani,in_combisu,out_combisu,notinout_combisu)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)
#'''
print('\n----match_combiで予想----')

saisinkekka=saisinkekka_list
bunkatu=5

kaisus = 50
sikichi = 1
pred_dlists=yobu_combi(dlists, kaisus, sikichi)

#kaisus = 50
#sikichi = 2
#pred_dlists=aisho_combi(dlists, kaisus, sikichi)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)

print('\n----match_combiで予想----')

saisinkekka=saisinkekka_list
bunkatu=5

#kaisus = 50
#sikichi = 1
#pred_dlists=yobu_combi(dlists, kaisus, sikichi)

kaisus = 50
sikichi = 2
pred_dlists=aisho_combi(dlists, kaisus, sikichi)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)

print('\n----match_combiで予想----')

saisinkekka=saisinkekka_list
bunkatu=5

kaisus = 50
sikichi = 1
yobu_lists = yobu_lists(dlists, kaisus, sikichi)

kaisus = 50
sikichi = 2
aisho_dcnt = aisho_dcnt(dlists, kaisus, sikichi)

sikichi = 4
pred_dlists=yobu_aisho_combi(dlists, yobu_lists, aisho_dcnt, sikichi)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)



Cloning into '2306_l6'...
remote: Enumerating objects: 320, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 320 (delta 19), reused 0 (delta 0), pack-reused 285
Receiving objects: 100% (320/320), 113.57 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (176/176), done.
saisinkekka_list [12, 14, 18, 25, 36, 42]
dlists [[12 14 18 25 36 42]
 [ 9 16 18 19 39 41]
 [ 1  9 34 35 39 42]
 [18 25 26 37 39 43]
 [ 6 12 13 15 17 41]]

----inner_outer_manuで予想----
----inner_outer----
inner_list [36, 42, 12, 14, 18, 25]
outer_list [1, 2, 4, 5, 6, 8, 9, 11, 14, 15, 16, 18, 19, 22, 23, 24, 26, 29, 30, 31, 32, 34, 35, 36, 37, 40, 41, 42, 43]
outer_list_not_inner [1, 2, 4, 5, 6, 8, 9, 11, 15, 16, 19, 22, 23, 24, 26, 29, 30, 31, 32, 34, 35, 37, 40, 41, 43]
----combi----
inner組合せ数 6
----combi----
outer組合せ数 53130
inner outer組合せ数 318780
----Dell6:コンストラクタ----
dlists:1550
pred_dlists:318780
合計範囲 outlist1>>len:2 type:<class 'list'>
[87, 177]
合計範囲内 ou

In [ ]:
from google.colab import drive
drive.mount('/content/drive')